In [1]:
import pandas as pd
import numpy as np
import math
import matplotlib.pyplot as plt

import plotly.graph_objects as go
from collections import Counter

from pymatreader import read_mat

In [2]:
GA1 = read_mat('GA1.mat')

/Users/kiristern/miniforge3/envs/tensorflow/lib/python3.9/site-packages/pymatreader/utils.py:224: UserWarning: pymatreader cannot import Matlab string variables. Please convert these variables to char arrays in Matlab.
  warn('pymatreader cannot import Matlab string variables. '


In [4]:
GA2 = read_mat('GA2.mat')
GA3 = read_mat('GA3.mat')
EA = read_mat('EA.mat')
H2O = read_mat('H2O.mat')

/Users/kiristern/miniforge3/envs/tensorflow/lib/python3.9/site-packages/scipy/io/matlab/mio.py:226: MatReadWarning: Duplicate variable name "None" in stream - replacing previous with new
Consider mio5.varmats_from_mat to split file into single variable files
  matfile_dict = MR.get_variables(variable_names)


In [5]:
jaabG1 = GA1['dat_JAABA']
jbG1 = GA1['dat_JB']

In [6]:
jaabG2 = GA2['dat_JAABA']
jbG2 = GA2['dat_JB']
jaabG3 = GA3['dat_JAABA']
jbG3 = GA3['dat_JB']
jaabEA = EA['dat_JAABA']
jbEA = EA['dat_JB']
jaabH2O = H2O['dat_JAABA']
jbH2O = H2O['dat_JB']

In [7]:
for key in jbG1:
    print(key)

xspine
yspine
AN
et
x
y
heading_direction


In [ ]:
for key in jaabG1:
    print(key)

In [12]:
jaabcond = jaabG1
jbcond = jbG1

In [ ]:
# round to whole degree
degree = []
for i in range(len(jbcond['heading_direction'])):
    for j in jbcond['heading_direction'][i]:
        degree.append(np.round(j,0))

In [ ]:
jbcond['heading_direction']

In [ ]:
jaabcond['pre_deg']

In [29]:
# need to change scalars to vectors
scalar_idx = []
head_at_turn = []

for i in range(len(jaabcond['pre_deg'])):
    if len(np.array([jaabcond['pre_deg'][i]]).shape) <= 1:
        scalar_idx.append(i) # get indices where it's a scalar
    else:
        head_at_turn.append(jaabcond['pre_deg'][i]) # append as normal

# remove all empty arrays (arrays of dims = 0)
head_at_turn = [i for i in head_at_turn if 0 not in i.shape]

# temp = []
# for i, j in enumerate(scalar_idx):
#      temp.append(jaabcond['pre_deg'][j]) # append as vector at the scalar idx
        
# pre_turn_deg = np.concatenate((head_at_turn, temp), axis=0)

In [ ]:
# to solve error above:
# turn_idx = []
head_at_turn = []
# for i in range(len(jaabG1['t0s'])):
#     turn_idx.append(np.searchsorted(jbG1['et'][i], jaabG1['t0s'][i]))
for i in range(len(jbG1['heading_direction'])): 
    flag = len(np.array([jaabG1['t0_idx'][i]]).shape) #here, I put the indices into a list and transfer it to np.array. 
                                            # If it's a scalar, it would be a 1-d array, if it's a list of indices, 
                                            # it would be a 2-d arrayso my naive idea was just to check how many dimension it has
    if flag>1: #when it's a list
        for j in jaabG1['t0_idx'][i]:
            head_at_turn.append(jbG1['heading_direction'][i][j]) #append as per normal
    else: # when it's a scalar
        head_at_turn.append(jbG1['heading_direction'][i][jaabG1['t0_idx'][i]]) #append at the scalar idx

In [30]:
head_at_turn

[array([  15.95355886,   21.88801126,  173.61673952,  108.3869222 ,
          38.71393234,  179.61675635,   92.05238345,   52.38604315,
         100.90502205,  133.00598139,  110.22793605,  100.81833945,
         -28.36567278,  -76.13106521, -156.9881414 ,   96.35611166,
         -35.74498141,  -50.4010008 , -172.13393163,   82.10636832]),
 array([  -7.69210165,   -3.52746805,   29.41279006,   43.48532032,
          31.66329455,  -59.27889222, -140.03408183,  152.35918378,
        -124.83958288,  -48.77361743, -112.21041465,   -1.42986295,
         -75.96375653,  -41.05481377,  141.80558044]),
 array([-110.27373097, -105.93635443,  -94.38881484,  -96.29563332,
        -103.97082669,  -96.03889594,  -21.83130813,  -77.1756019 ]),
 array([-147.20046873,  167.96279768,  151.45575268]),
 array([ -46.7544573 , -162.3348138 ,   87.51584064,  157.27764842]),
 array([ -35.60055264, -110.49734055,  -28.05614473]),
 array([-146.49656302,  158.17766437,  174.14687101]),
 array([  82.81573261, -15

In [ ]:
head_turn_list = []
for i in range(len(head_at_turn)):
    temp.append(head_at_turn[i].flatten().tolist())

In [ ]:
head_turn_list

In [ ]:
# get frequency of degrees
dict_deg = Counter(head_turn_list[0])
dict_deg

In [ ]:
# fig = go.Figure(data=
#     go.Scatterpolar(
#         r = list(dict_deg.values()),
#         theta = list(dict_deg.keys()),
#         mode = 'markers',
#     ))

# fig.update_layout(showlegend=False)
# fig.show()

In [ ]:
fig = go.Figure(go.Barpolar(
    r= list(dict_deg.values()), # degree counts
    theta= list(dict_deg.keys()), #degree angle
    #width=[20,15,10,20,15,30,15,],
    #marker_color=["#E4FF87", '#709BFF', '#709BFF', '#FFAA70', '#FFAA70', '#FFDF70', '#B6FFB4'],
    #marker_line_color="black",
    #marker_line_width=0.5,
    #opacity=0.8
))

# fig.update_layout(
#     template=None,
#     polar = dict(
#         radialaxis = dict(range=[0, 5], showticklabels=False, ticks=''),
#         angularaxis = dict(showticklabels=False, ticks='')
#     )
# )

fig.show()

In [ ]:
jbG1['x'][0].shape

In [ ]:
def angdiff(a1, a2):
    angle = 180 - abs(abs(a1 - a2) - 180)
    return angle

In [ ]:
def angdistance(unit1, unit2):
    phi = abs(unit2-unit1) % 360
    sign = 1
    # used to calculate sign
    if not ((unit1-unit2 >= 0 and unit1-unit2 <= 180) or (
            unit1-unit2 <= -180 and unit1-unit2 >= -360)):
        sign = -1
    if phi > 180:
        result = 360-phi
    else:
        result = phi

    return result*sign

In [ ]:
# get index for when turn occurs --- INDICES ARE ALREADY CALCULATED in 't0_idx' and 't1_idx'
turn_idx=[]
for i in range(len(jaabG1['t0s'])):
    turn_idx.append(np.searchsorted(jbG1['et'][i], jaabG1['t0s'][i])) #idex of jbG1['et'] that matches time of turn

In [ ]:
for i in range(len(jbG1['heading_direction'])):
    print(jaabG1['t0_idx'][i]) # throws error because when there's only 1 turn, it is a scalar (not vector)
    head_at_turn = [jbG1['heading_direction'][i][j] for j in jaabG1['t0_idx'][i]]

In [23]:
# to solve error above:
# turn_idx = []
head_at_turn = []
# for i in range(len(jaabG1['t0s'])):
#     turn_idx.append(np.searchsorted(jbG1['et'][i], jaabG1['t0s'][i]))
for i in range(len(jbG1['heading_direction'])): 
    flag = len(np.array([jaabG1['t0_idx'][i]]).shape) #here, I put the indices into a list and transfer it to np.array. 
                                            # If it's a scalar, it would be a 1-d array, if it's a list of indices, 
                                            # it would be a 2-d arrayso my naive idea was just to check how many dimension it has
    if flag>1: #when it's a list
        for j in jaabG1['t0_idx'][i]:
            head_at_turn.append(jbG1['heading_direction'][i][j]) #append as per normal
    else: # when it's a scalar
        head_at_turn.append(jbG1['heading_direction'][i][jaabG1['t0_idx'][i]]) #append at the scalar idx

In [27]:
turn_idx=[]
head_at_turn = []

for i in range(len(jaabG1['t0s'])):
    turn_idx.append(np.searchsorted(jbG1['et'][i], jaabG1['t0s'][i]))
for i in range(len(jbG1['heading_direction'])): 
    flag = len(np.array([turn_idx[i]]).shape) #here, I put the indices into a list and transfer it 
                                             # to np.array. If it's a scalar, it would be a 1-d         
                                             #  array, if it's a list of indices, it would be a 2-d array
                                             #  so my naive idea was just to check how many dimension it has
    if flag>1:
        for j in turn_idx[i]:
            head_at_turn.append(jbG1['heading_direction'][i][j])
    else:
        head_at_turn.append(jbG1['heading_direction'][i][turn_idx[i]])

In [28]:
head_at_turn

[13.676180465475301,
 14.027987591972577,
 -23.58061883496325,
 90.31155636104879,
 32.776544813954274,
 32.302785847135,
 -97.55018701801677,
 -16.41078459687728,
 121.9353272680449,
 127.53331717313439,
 101.25891220298818,
 83.54885766144876,
 126.18375344801018,
 106.09154447831799,
 24.365294116602414,
 -76.15972562434375,
 -30.863193617323674,
 -64.34749731022747,
 -15.405107312044992,
 80.6579386218423,
 -4.876997301814941,
 -4.080520650884756,
 24.487585745975036,
 53.681192249678396,
 32.57165235069472,
 -60.68286375090139,
 -144.47924524962653,
 157.8511561973854,
 -119.16231471549887,
 -56.80603981352497,
 -105.07696449340656,
 8.436301341540306,
 -54.219859435994884,
 -34.250793202552074,
 140.59998684888996,
 -107.8929184982756,
 -83.62416705575555,
 -96.12693300549421,
 -104.20204739508056,
 -97.25229180515716,
 -84.16571249209397,
 -18.54527976841468,
 -75.75322450235856,
 -155.98520841746333,
 154.9222849561741,
 149.9589867876233,
 -44.215699421405105,
 168.68410852657

In [ ]:
# get distribution of heading_direction
jbG1['heading_direction']

In [ ]:
for i in range(len(jbG1['heading_direction'])):
    plt.hist(jbG1['heading_direction'][i], bins=9)

In [ ]:
plt.hist(jbG1['heading_direction'][0], bins=358)